create database qldienmay
on primary
(
	name=qldienmay,
	filename='E:\SQL\qldienmay.mdf',
	size=20mb,
	filegrowth=5mb
)
create table GIOHANG(
	MAGH nvarchar(30) primary key,
	MASP nvarchar(30),
	MAKH nvarchar(30),
	TENSP nvarchar(30),
	LOAISP NVARCHAR(30),
	SOLUONG INT
)
CREATE TABLE KHACHHANG(
	MAKH NVARCHAR(30) PRIMARY KEY,
	TENKH NVARCHAR(30),
	EMAIL NVARCHAR(30),
	SDT NVARCHAR(20),
	DCHI NVARCHAR(50)
)
CREATE TABLE GIAOHANG(
	MAKH NVARCHAR(30),
	SOHD NVARCHAR(30),
	NGAYGIAO SMALLDATETIME,
	DIACHI NVARCHAR(50),
	PRIMARY KEY (MAKH,SOHD)
)
CREATE TABLE TKNGANHANG(
	SOTK NVARCHAR(30) PRIMARY KEY,
	MAKH NVARCHAR(30),
	TENKH NVARCHAR(30),
	MAPIN NVARCHAR(30),
	TENNGANHANG NVARCHAR(30)
)
CREATE TABLE DONHANG(
	SOHD NVARCHAR(30) PRIMARY KEY,
	MAKH NVARCHAR(30),
	MASP NVARCHAR(30),
	NGAYHD SMALLDATETIME,
	SOLUONG INT,
	THANHTIEN MONEY
)
CREATE TABLE THANHTOAN(
	MATT NVARCHAR(30) PRIMARY KEY,
	HINHTHUC NVARCHAR(30),
	SOHD NVARCHAR(30),
	TONGTIEN MONEY,
	NGAYTT SMALLDATETIME 
)
CREATE TABLE TAIKHOAN(
	MATK NVARCHAR(30) PRIMARY KEY,
	TENTK NVARCHAR(30),
	MATKHAU NVARCHAR(30),
	MAKH NVARCHAR(30),
	MANV NVARCHAR(30),
	MAQL NVARCHAR(30)
)

CREATE TABLE SANPHAM(
	MASP NVARCHAR(30) PRIMARY KEY,
	TENSP NVARCHAR(30),
	LOAISP NVARCHAR(30),
	HANGSX NVARCHAR(30),
	DONGIA NVARCHAR(30)
)
CREATE TABLE QUANLY(
	MAQL NVARCHAR(30) PRIMARY KEY,
	TENQL NVARCHAR(30),
	EMAIL NVARCHAR(30),
	SDT NVARCHAR(20)
)
CREATE TABLE BAOCAO(
	MABC NVARCHAR(30) PRIMARY KEY,
	MANV NVARCHAR(30),
	NGAYBC SMALLDATETIME
)
CREATE TABLE NHANVIEN(
	MANV NVARCHAR(30) PRIMARY KEY,
	TENNV NVARCHAR(30),
	CHUCVU NVARCHAR(20),
	SDT NVARCHAR(20),
	EMAIL NVARCHAR(30),
	DCHI NVARCHAR(30)
)
CREATE TABLE CT_HD(
	SOHD NVARCHAR(30),
	MASP NVARCHAR(30),
	SOLUONG INT,
	DONGIA MONEY,
	PRIMARY KEY (SOHD,MASP)
)


