//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHMAYTINH
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public string MAKH { get; set; }
        public string TENKH { get; set; }
        public string EMAIL { get; set; }
        public string SDT { get; set; }
        public string DCHI { get; set; }
        public string TAIKHOAN { get; set; }
        public string GHICHU { get; set; }
    }
}
