//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHMAYTINH
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAISANPHAM
    {
        public string MALOAIHH { get; set; }
        public string TENLOAI { get; set; }
        public string ANHMH { get; set; }
        public string GHICHU { get; set; }
    }
}
