//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCHMAYTINH
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAPHANPHOI
    {
        public string MANPP { get; set; }
        public string TENNPP { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public string TAIKHOAN { get; set; }
        public string MSTHUE { get; set; }
        public string GHICHU { get; set; }
    }
}
